package edu.fudan.nisl.jaq.model;

// Generated 2014-11-3 14:45:56 by Hibernate Tools 3.4.0.CR1

/**
 * User generated by hbm2java
 */
public class Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String usersName;
	private String usersPassword;
	private String usersPhone;
	private String usersEmail;
	private Long usersRoleId;
	private String usersInfo;

	public Users() {
	}

	public Users(int id, String usersName) {
		this.id = id;
		this.usersName = usersName;
	}

	public Users(int id, String usersName, String usersPassword,
			String usersPhone, String usersEmail, Long usersRoleId, String usersInfo) {
		this.id = id;
		this.usersName = usersName;
		this.usersPassword = usersPassword;
		this.usersPhone = usersPhone;
		this.usersEmail = usersEmail;
		this.usersRoleId = usersRoleId;
		this.usersInfo = usersInfo;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUsersName() {
		return this.usersName;
	}

	public void setUsersName(String usersName) {
		this.usersName = usersName;
	}

	public String getUsersPassword() {
		return this.usersPassword;
	}

	public void setUsersPassword(String usersPassword) {
		this.usersPassword = usersPassword;
	}

	public String getUsersPhone() {
		return this.usersPhone;
	}

	public void setUsersPhone(String usersPhone) {
		this.usersPhone = usersPhone;
	}

	public String getUsersEmail() {
		return this.usersEmail;
	}

	public void setUsersEmail(String usersEmail) {
		this.usersEmail = usersEmail;
	}

	public Long getUsersRoleId() {
		return this.usersRoleId;
	}

	public void setUsersRoleId(Long usersRoleId) {
		this.usersRoleId = usersRoleId;
	}

	public String getUsersInfo() {
		return this.usersInfo;
	}

	public void setUsersInfo(String usersInfo) {
		this.usersInfo = usersInfo;
	}

}
